services:
    postgres:
        image: postgres:18.3
        restart: unless-stopped
        env_file:
            - .env
        hostname: ${POSTGRES_HOST}
        command: -p ${POSTGRES_PORT}
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - "5432:${POSTGRES_PORT}"
        volumes:
            - ./postgres/scripts/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
            - ./postgres/scripts/fill.sql:/docker-entrypoint-initdb.d/02-fill.sql:ro
    redis:
        image: redis:8.6-alpine
        restart: unless-stopped
        env_file:
            - .env
        hostname: ${REDIS_HOST}
        command: >
            sh -c "
            chmod +x /init.sh && 
            /init.sh
            "
        volumes:
            - ./redis/init.sh:/init.sh
        ports:
            - "6379:${REDIS_PORT}"

# Для запуска: docker-compose -f docker-compose.yaml up -d
# Для остановки: docker-compose -f docker-compose.yaml down