server:
    address: 0.0.0.0
    port: ${SPRING_PORT}
spring:
    datasource:
        url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: false
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    data:
        redis:
            host: ${REDIS_HOST}
            port: ${REDIS_PORT}
            username: ${REDIS_USERNAME}
            password: ${REDIS_PASSWORD}
    mail:
        host: ${MAIL_HOST}
        port: ${MAIL_PORT}
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: ${MAIL_AUTH}
                    starttls:
                        enable: ${MAIL_STARTTLS}
    threads:
        virtual:
            enabled: true
    web:
        resources:
            static-locations:
                - "file:/static"
springdoc:
    swagger-ui:
        urls:
            -   name: Auth API
                url: /api/auth-swagger-api.yaml
            -   name: Bookings API
                url: /api/bookings-swagger-api.yaml
            -   name: Cells API
                url: /api/cells-swagger-api.yaml
            -   name: Operators API
                url: /api/operators-swagger-api.yaml
            -   name: Payments API
                url: /api/payments-swagger-api.yaml
            -   name: Prices API
                url: /api/prices-swagger-api.yaml
            -   name: Storages API
                url: /api/storages-swagger-api.yaml
            -   name: Users API
                url: /api/users-swagger-api.yaml

skladinya:
    jwt:
        issuer: ${JWT_ISSUER}
        secret: ${JWT_SECRET}
        ttl: ${JWT_TTL}
    booking:
      payment-timeout-minutes: 15