rootProject.name = "sklaDinya"
include(":domain")
include(":application")
include(":services-auth")
include(":persistence-postgres")
include(":persistence-redis")
include(":tests-helper")
include(":tests-unit")
include(":tests-integration")
include(":tests-e2e")