rootProject.name = "sklaDinya"
include(":application")
include(":domain")
include(":services-auth")
include(":services-cell")
include(":services-email")
include(":services-jwt")
include(":services-operator")
include(":services-storage")
include(":services-user")
include(":persistence-postgres")
include(":persistence-redis")
include(":tests-helper")
include(":tests-unit")
include(":tests-integration")
include(":tests-e2e")
include(":utils-bdfiller")