rootProject.name = "sklaDinya"
include(":application")
include(":domain")
include(":services-auth")
include(":services-jwt")
include(":services-storage")
include(":services-user")
include(":services-booking")
include(":services-booking-update")
include(":services-payment")
include(":services-price")
include(":persistence-postgres")
include(":persistence-redis")
include(":tests-helper")
include(":tests-unit")
include(":tests-integration")
include(":tests-e2e")
include(":utils-bdfiller")